# Generated by Django 5.0.1 on 2024-01-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='working',
            field=models.BooleanField(default=False),
        ),
    ]
