# Generated by Django 5.0.1 on 2024-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
